name: ZAMAT Android · preparación V0.1.3

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Preparación
        run: echo "Publicación V0.1.3 temporalmente en preparación"
